### ISSUE TITLE
bug: el fondo no llega hasta el fondo vertical (abajo)

### ISSUE THREAD

**Issue by novia713** [novia713/tilescreen#5]
cuando no está habilitada la opción de transparencia, según @pancake no llega el color de fondo hasta abajo del todo

**Comment by novia713** [comment]
creo que esto ya no pasa
¿te sigue pasando, @radare ?

**Comment by radare** [comment]
Cierra. Va guai esto ahora

**Comment by radare** [comment]
Pero me gusta mas transparente

**Comment by novia713** [comment]
pulsando en el tile con información y la fecha sale una opción para ponerlo transparente ....

**Comment by radare** [comment]
Pues no la
He vistoZz volvere a probar cuando tenga tiempo thx
